#!/bin/bash
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/festmyb02.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/festemyb03.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/festemyb04.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/festemyb05.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2006-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2007-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2008-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2009-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2010-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2011-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2012-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2013-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2014-feste.xls'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/mineral-pubs/iron-steel/myb1-2015-feste.xls'
wget -Uxx 'https://d9-wret.s3-us-west-2.amazonaws.com/assets/palladium/production/atoms/files/myb1-2016-feste.xls'
wget -Uxx 'https://prd-wret.s3-us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/atoms/files/myb1-2016-feste-adv.xlsx'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/atoms/files/myb1-2017-feste.xls'
wget -Uxx 'https://prd-wret.s3-us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/atoms/files/myb1-2016-feste-adv.xlsx'
wget -Uxx 'https://pubs.usgs.gov/myb/vol1/2018/myb1-2018-iron-steel.xlsx'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/atoms/files/myb1-2019-feste-adv.xlsx'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/media/files/myb1-2020-feste-advrel.xlsx'
wget -Uxx 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/media/files/myb1-2021-feste-ert.xlsx'

