wget -O KOR.html https://sport.onet.pl/mundial-2018/reprezentacja-korei-poludniowej/kadra-korei-poludniowej-na-mundial-2018-sklad-reprezentacji-na-ms/g05lwnq
wget -O CRC.html https://sport.onet.pl/mundial-2018/reprezentacja-kostaryki/kadra-kostaryki-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/zd8tcq1
wget -O MEX.html https://sport.onet.pl/mundial-2018/reprezentacja-meksyku/kadra-meksyku-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/ryrt4zj
wget -O MAR.html https://sport.onet.pl/mundial-2018/reprezentacja-maroko/kadra-maroka-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/9dp5rtf
wget -O GER.html https://sport.onet.pl/mundial-2018/reprezentacja-niemiec/kadra-niemiec-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/08jnp34
wget -O NGR.html 'https://sport.onet.pl/mundial-2018/reprezentacja-nigerii/kadra-nigerii-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/1rxkpz1?utm_source=sport_viasg&utm_medium=nitro&utm_campaign=allonet_nitro_new&srcc=ucs&utm_v=2'
wget -O PAN.html https://sport.onet.pl/mundial-2018/reprezentacja-panamy/kadra-panamy-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/t05llhg
wget -O PER.html 'https://sport.onet.pl/mundial-2018/reprezentacja-peru/kadra-peru-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/v0db278?utm_source=sport_viasg&utm_medium=nitro&utm_campaign=allonet_nitro_new&srcc=ucs&utm_v=2'
wget -O POR.html https://sport.onet.pl/mundial-2018/reprezentacja-portugalii/kadra-portugalii-na-mundial-2018-sklad-na-ms-w-pilce-noznej/hzhr9h7
wget -O RUS.html https://sport.onet.pl/mundial-2018/reprezentacja-rosji/kadra-rosji-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/yjh4fxb
wget -O SEN.html https://sport.onet.pl/mundial-2018/reprezentacja-senegalu/kadra-senegalu-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/xptlqqz
wget -O SRB.html 'https://sport.onet.pl/mundial-2018/reprezentacja-serbii/kadra-serbii-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/75s67bj?utm_source=sport_viasg&utm_medium=nitro&utm_campaign=allonet_nitro_new&srcc=ucs&utm_v=2'
wget -O SWE.html https://sport.onet.pl/mundial-2018/reprezentacja-szwecji/kadra-szwecji-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/qn5jzvl
wget -O SUI.html https://sport.onet.pl/mundial-2018/reprezentacja-szwajcarii/kadra-szwajcarii-na-mundial-2018-sklad-reprezentacji-na-ms-w-rosji/d31h38s
wget -O TUN.html 'https://sport.onet.pl/mundial-2018/reprezentacja-tunezji/kadra-tunezji-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/8yrwm47?utm_source=sport_viasg&utm_medium=nitro&utm_campaign=allonet_nitro_new&srcc=ucs&utm_v=2'
wget -O URU.html 'https://sport.onet.pl/mundial-2018/reprezentacja-urugwaju/kadra-urugwaju-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/vb49jkd?utm_source=sport_viasg&utm_medium=nitro&utm_campaign=allonet_nitro_new&srcc=ucs&utm_v=2'
wget -O POL.html https://sport.onet.pl/mundial-2018/reprezentacja-polski/kadra-polski-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/gn194qk
wget -O ENG.html https://sport.onet.pl/mundial-2018/reprezentacja-anglii/kadra-anglii-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/p8vdfk1
wget -O SAR.html 'https://sport.onet.pl/mundial-2018/reprezentacja-arabii-saudyjskiej/kadra-arabii-saudyjskiej-na-mundial-2018-sklad-reprezentacji-na-ms/epe5ppx?utm_source=sport_viasg&utm_medium=nitro&utm_campaign=allonet_nitro_new&srcc=ucs&utm_v=2'
wget -O ARG.html https://sport.onet.pl/mundial-2018/reprezentacja-argentyny/kadra-argentyny-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/yxvdd7y
wget -O AUS.html https://sport.onet.pl/mundial-2018/reprezentacja-australii/kadra-australii-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/d7swkwz
wget -O BEL.html https://sport.onet.pl/mundial-2018/reprezentacja-belgii/kadra-belgii-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/cy65mjy
wget -O BRA.html https://sport.onet.pl/mundial-2018/reprezentacja-brazylii/kadra-brazylii-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/l2ve20m
wget -O CRO.html https://sport.onet.pl/mundial-2018/reprezentacja-chorwacji/kadra-chorwacji-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/cqleqkz
wget -O DEN.html 'https://sport.onet.pl/mundial-2018/reprezentacja-danii/kadra-danii-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/n5p4pvv?utm_source=sport_viasg&utm_medium=nitro&utm_campaign=allonet_nitro_new&srcc=ucs&utm_v=2'
wget -O EGY.html https://sport.onet.pl/mundial-2018/reprezentacja-egiptu/kadra-egiptu-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/jn5m9nt
wget -O FRA.html https://sport.onet.pl/mundial-2018/reprezentacja-francji/kadra-francji-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/zcvxbek
wget -O ESP.html https://sport.onet.pl/mundial-2018/reprezentacja-hiszpanii/kadra-hiszpanii-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/fxg30yd
wget -O ISLhtml https://sport.onet.pl/mundial-2018/reprezentacja-islandii/kadra-islandii-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/4v46q4z
wget -O IRA.html https://sport.onet.pl/mundial-2018/reprezentacja-iranu/kadra-iranu-na-mundial-2018-sklad-reprezentacji-na-ms-w-pilce-noznej/j4dvw5g
wget -O JPN.html https://sport.onet.pl/mundial-2018/reprezentacja-japonii/kadra-japonii-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/jeq8x9d
wget -O COL.html https://sport.onet.pl/mundial-2018/reprezentacja-kolumbii/kadra-kolumbii-na-mundial-2018-sklad-reprezentacji-ms-w-pilce-noznej/fre295f
###

